[tool.black]
line-length = 100
skip-string-normalization = 1

[tool.ruff]
target-version = "py37" # rainbow-version
line-length = 100
exclude = [".venv", "ap/script"]
fixable = ["ALL"]
select = [
#    "C4", # comprehensions
#    "COM", # trailing comma
#    "E", # style errors
#    "EXE", # shebang
#    "F", # flakes
#    "G", # logging format
    "I", # import sorting
#    "INT", # gettext
#    "ISC", # string concatenation
#    "PIE", # miscellaneous
#    "PL", # pylint
    "Q", # quotes
#    "RSE", # raise
#    "SIM", # simplify
#    "T10", # debugger
#    "W", # style warnings
#    "YTT", # sys.version
    "N801",
    "N802",
    "N804",
    "N805",
    "N812",
    "N814",
    "N999",
]
ignore = [
    "C416",

    "E402",
    "E501",
    "E711", # Comparison with None

    "F405",
    "F403",
    "F821",
    "E722",
    "F811", # Redefinition of unused

    "G001",
    "G002",
    "G004",

    "SIM102",
    "SIM105",
    "SIM108",
    "SIM112",
    "SIM114",
    "SIM115",
    "SIM118",
    "PIE804", # Unnecessary `dict` kwargs
    "PLC0208", # Use a sequence type instead of a `set` when iterating over values

    "PLR0124", # Name compared with itself
    "PLR0911",
    "PLR0912",
    "PLR0913",
    "PLR0915",
    "PLR2004",
    "PLR5501",

    "PLW0120", # `else` clause on loop without a `break` statement
    "PLW0602",
    "PLW0603",
    "PLW2901",

]


[tool.ruff.extend-per-file-ignores]
"tests/units/*py" = ["E501", "F405", "F403", "PLR0133", "PLR0912", "PLR0915", "PLW"]
"migrations/*" = ["G", "PLR0912"]
"manage.py" = ["F403", "F405"]
"wrapr_utils.py" = ["E501"]

[tool.ruff.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"
multiline-quotes = "single"
